name: hello-world
on: push 
jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_word.txt)"
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          note-version: '18.x'
      - run: npm intall 
      - run: npm build 
